language: python
dist: trusty
sudo: required
cache: pip

python:
  - 3.4
  - 3.5
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - export CYTHON_TRACE=1
  - python setup.py install
  - python setup.py build_ext --inplace
  - pytest --cov=piqueserver --cov=pyspades
  - coveralls
  # - pylint piqueserver
  # - pylint pyspades

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MG5vdGFmaWxlJTNBbWF0cml4Lm9yZy8lMjFzcFNwVVNjSmplcmJsWGlWekElM0FtYXRyaXgub3Jn"
        on_success: change  # always|never|change
        on_failure: change
        on_start: never
        on_cancel: never
