language: python
dist: xenial
sudo: required
cache: pip

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - sudo apt-get install -y libenchant-dev
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - export CYTHON_TRACE=1
  - python setup.py develop
  - pytest --cov=piqueserver --cov=pyspades
  - travis_retry coveralls
  # - pylint piqueserver
  # - pylint pyspades

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MG5vdGFmaWxlJTNBbWF0cml4Lm9yZy8lMjFzcFNwVVNjSmplcmJsWGlWekElM0FtYXRyaXgub3Jn"
        on_success: change  # always|never|change
        on_failure: change
        on_start: never
        on_cancel: never
