version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
shallow_clone: true

environment:
  PATH: '%PYTHON%;%PYTHON%\Scripts;%PATH%'
  matrix:
  - PYTHON: C:\Python36-x64
  - PYTHON: C:\Python35-x64
  - PYTHON: C:\Python37-x64
  - PYTHON: C:\Python36
  - PYTHON: C:\Python35
  - PYTHON: C:\Python37

install:
- cmd: >-
    python -m pip install -U pip wheel setuptools

    pip --version

    if defined DO_EXE (pip install -U pyinstaller)

    pip install -r requirements.txt

    pip install -r dev-requirements.txt

build_script:
- cmd: >-
    python --version

    python setup.py build_ext --inplace -c msvc

    python setup.py build -c msvc

    python setup.py sdist

    python setup.py bdist_wheel

test_script:
- cmd: pytest

artifacts:
- path: dist/*

deploy: off
