version: '3.6'

services:
    piqueserver:
        build:
            context: .
            dockerfile: dev.Dockerfile
        volumes:
            - ./piqueserver/config:/config
            - ./:/app/src/
